import { generateTypographyAttributes, generateDimensionsAttributes } from "./helpers";

const attributes = {
	resOption: {
		type: "string",
		default: "desktop",
	},
	blockId: {
		type: "string",
	},
	blockRoot: {
		type: "string",
		default: "essential_block",
	},
	blockMeta: {
		type: "object",
	},
	avaterContainerFontSize: {
		type: "number",
		default: 16,
	},
	displayAvatar: {
		type: "boolean",
		default: true,
	},
	avatarInline: {
		type: "boolean",
		default: true,
	},
	avatarPosition: {
		type: "string",
		default: "flex-start",
	},
	avatarAlign: {
		type: "string",
		default: "center",
	},
	borderRadius: {
		type: "number",
		default: 50,
	},
	imageUrl: {
		type: "string",
	},
	imageId: {
		type: "string",
	},
	avatarOrder: {
		type: "number",
		default: 1,
	},
	userName: {
		selector: ".eb-testimonial-username",
		source: "html",
		default: "John Doe",
	},
	companyName: {
		selector: ".eb-testimonial-company",
		source: "html",
		default: "Company Name",
	},
	description: {
		selector: ".eb-testimonial-description",
		source: "html",
		default:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
	},
	textAlign: {
		type: "string",
		default: "center",
	},
	userInfoPos: {
		type: "string",
		default: "flex-start",
	},
	imagePosition: {
		type: "number",
		default: 0,
	},
	userNameColor: {
		type: "string",
		default: "#7967ff",
	},
	descriptionColor: {
		type: "string",
		default: "#4a5059",
	},
	quoteColor: {
		type: "string",
		default: "#edf1f7",
	},
	quoteSize: {
		type: "number",
		default: 60,
	},
	userInfoAlign: {
		type: "string",
		default: "center",
	},
	backgroundColor: {
		type: "string",
		default: "transparent",
	},
	backgroundImageURL: {
		type: "string",
	},
	//Margin
	linkedMargin: {
		type: "boolean",
		default: false,
	},
	//Padding
	linkedPadding: {
		type: "boolean",
		default: false,
	},

	shadowColor: {
		type: "string",
		default: "#000000",
	},
	shadowHOffset: {
		type: "number",
	},
	shadowVOffset: {
		type: "number",
	},
	shadowBlur: {
		type: "number",
	},
	shadowSpread: {
		type: "number",
	},
	marginUnit: {
		type: "string",
		default: "px",
	},
	tabMarginUnit: {
		type: "string",
		default: "px",
	},
	mobMarginUnit: {
		type: "string",
		default: "px",
	},
	paddingUnit: {
		type: "string",
		default: "px",
	},
	tabPaddingUnit: {
		type: "string",
		default: "px",
	},
	mobPaddingUnit: {
		type: "string",
		default: "px",
	},
	nameSizeUnit: {
		type: "string",
		default: "px",
	},
	companySizeUnit: {
		type: "string",
		default: "px",
	},
	descriptionSizeUnit: {
		type: "string",
		default: "px",
	},
	quoteSizeUnit: {
		type: "string",
		default: "px",
	},
	companyColor: {
		type: "string",
		default: "#4a5059",
	},
	backgroundType: {
		type: "string",
		default: "color",
	},
	
	bgPositon: {
		type: "string",
	},
	bgXPos: {
		type: "number",
		default: 0,
	},
	bgXPosUnit: {
		type: "string",
		default: "%",
	},
	bgYPos: {
		type: "number",
		default: 0,
	},
	bgYPosUnit: {
		type: "string",
		default: "%",
	},
	bgSize: {
		type: "string",
	},
	bgWidth: {
		type: "number",
	},
	bgWidthUnit: {
		type: "string",
		default: "%",
	},
	bgRepeat: {
		type: "string",
	},
	bgAttachment: {
		type: "string",
	},
	/**
	 * Autogenerated Attributes
	*/
	// margin attributes ⬇
	...generateDimensionsAttributes('margin', {
		top: 10,
		bottom: 10,
		right: 10,
		left: 10,
	}),
	// padding attributes ⬇
	...generateDimensionsAttributes('padding', {
		top: 10,
		bottom: 10,
		right: 10,
		left: 10,
	}),
	// typography attributes ⬇
	...generateTypographyAttributes(Object.values({username: 'username', company: 'company', description: 'description'})),
};

export default attributes;
